### ISSUE TITLE
Chart by major version

### ISSUE THREAD

**Issue by Eomm** [atinux/npm-chart#4]
Hi,  
I'm sharing an idea here: displays the download count by a module's major version.

Considering that each major version has a different timeline, the starting point for every line would be the release date, so the X-axis would be:

- Week 1
- Week 2
- etc.

Without the actual time.

---

Another visualization could be a stacked bar.

---

This graph would help to understand how (and if) the community is keeping their codebase up to date and whether a major release was successful or not.

**Comment by atinux** [comment]
Hi @Eomm I don't have the info using the current API.

But did you know about https://craigory.dev/npm-burst/?package=vue&sortBy=version ?

**Comment by Eomm** [comment]
wow, no - I didn't know it!

> I don't have the info using the current API.

I checked the source code, and it is using this [public API](https://github.com/AgentEnder/npm-burst/blob/c436ce2835373905af62a7c1b4253b2f3795f590/libs/npm/data-access/src/lib/npm-client.ts#L11) `https://api.npmjs.org/versions/fastify/last-week` in case

**Comment by atinux** [comment]
Yes me too, but it will be only the last week downloads per version
